const films = [
  { emoji: "🧙‍♂️💍🌋", reponse: "Le Seigneur des Anneaux" },
  { emoji: "🧑‍🚀🌕🚀", reponse: "Interstellar" },
  { emoji: "🦁👑🌍", reponse: "Le Roi Lion" },
  { emoji: "🦖🏝️", reponse: "Jurassic Park" },
  { emoji: "🧛‍♂️🩸🏰", reponse: "Dracula" },
  { emoji: "🤠🔫🌵", reponse: "Le Bon, la Brute et le Truand" },
  { emoji: "🚢💔🌊", reponse: "Titanic" },
  { emoji: "🧠🔪🚿", reponse: "Psychose" },
  { emoji: "👽📞🌍", reponse: "E.T." },
  { emoji: "🕶️💊🖥️", reponse: "Matrix" },
  { emoji: "🦇🤵‍♂️🌃", reponse: "Batman" },
  { emoji: "🕷️🧑‍🦱🏙️", reponse: "Spider-Man" },
  { emoji: "🧑‍🎤👑🎵", reponse: "Bohemian Rhapsody" },
  { emoji: "🚗⚡🏁", reponse: "Fast and Furious" },
  { emoji: "🧊👸❄️", reponse: "La Reine des Neiges" },
  { emoji: "👻🔫🏙️", reponse: "SOS Fantômes" },
  { emoji: "🦈🌊🚤", reponse: "Les Dents de la Mer" },
  { emoji: "🧑‍🚀🤖🌌", reponse: "Star Wars" },
  { emoji: "🧙‍♂️⚡🏰", reponse: "Harry Potter" },
  { emoji: "🦸‍♂️🛡️🇺🇸", reponse: "Captain America" },
  { emoji: "🤖🔥🚗", reponse: "Terminator" },
  { emoji: "🧑‍🚀🪐🌽", reponse: "Seul sur Mars" },
  { emoji: "🎭🔪🩸", reponse: "Scream" },
  { emoji: "🧠💭😴", reponse: "Inception" },
  { emoji: "🧑‍⚖️⚖️📜", reponse: "Le Parrain" },
  { emoji: "🐼🥋🏔️", reponse: "Kung Fu Panda" },
  { emoji: "👴🎈🏠", reponse: "Là-Haut" },
  { emoji: "🧑‍🍳🐀🍝", reponse: "Ratatouille" },
  { emoji: "🚗🧑‍🚒🔥", reponse: "Cars" },
  { emoji: "🧑‍🎓📚✨", reponse: "Harry Potter à l’école des sorciers" },
  { emoji: "👮‍♂️🏢💥", reponse: "Die Hard" },
  { emoji: "🧑‍🚀🌕🐒", reponse: "La Planète des Singes" },
  { emoji: "👽🔫🕶️", reponse: "Men in Black" },
  { emoji: "🧛‍♀️🐺🌕", reponse: "Twilight" },
  { emoji: "🧑‍✈️🛫🏝️", reponse: "Seul au monde" },
  { emoji: "🎩🐰⏳", reponse: "Alice au Pays des Merveilles" },
  { emoji: "🤡🎈🚲", reponse: "Ça" },
  { emoji: "🧑‍🚀🤖❤️", reponse: "Wall-E" },
  { emoji: "🦸‍♂️⚡🌩️", reponse: "Thor" },
  { emoji: "🧑‍🎤🎸🎶", reponse: "Rocketman" },
  { emoji: "👶🧔🔫", reponse: "Leon" },
  { emoji: "🧑‍🚀🚀🌍", reponse: "Gravity" },
  { emoji: "🧑‍⚖️🔍🧠", reponse: "Seven" },
  { emoji: "🤠🐎🌄", reponse: "Il était une fois dans l’Ouest" },
  { emoji: "👨‍👩‍👧‍👦🧬🦖", reponse: "Jurassic World" },
  { emoji: "🧑‍🚀🌌🌀", reponse: "2001, l’Odyssée de l’espace" },
  { emoji: "🎩🪄🎥", reponse: "The Prestige" },
  { emoji: "👻🏨❄️", reponse: "Shining" },
  { emoji: "🧑‍🚀🧠🤯", reponse: "Premier Contact" },
  { emoji: "🦸‍♂️🕷️🕸️", reponse: "Spider-Man No Way Home" }
];
