const films = [
  { emojis: "🧙‍♂️💍🌋", title: "Le Seigneur des Anneaux" },
  { emojis: "🧑‍🚀🌕🚀", title: "Interstellar" },
  { emojis: "🦁👑🌍", title: "Le Roi Lion" },
  { emojis: "🦖🏝️", title: "Jurassic Park" },
  { emojis: "🧛‍♂️🩸🏰", title: "Dracula" },
  { emojis: "🤠🔫🌵", title: "Le Bon, la Brute et le Truand" },
  { emojis: "🚢💔🌊", title: "Titanic" },
  { emojis: "🧠🔪🚿", title: "Psychose" },
  { emojis: "👽📞🌍", title: "E.T." },
  { emojis: "🕶️💊🖥️", title: "Matrix" },

  { emojis: "🦇🤵‍♂️🌃", title: "Batman" },
  { emojis: "🕷️🧑‍🦱🏙️", title: "Spider-Man" },
  { emojis: "🧑‍🎤👑🎵", title: "Bohemian Rhapsody" },
  { emojis: "🚗⚡🏁", title: "Fast and Furious" },
  { emojis: "🧊👸❄️", title: "La Reine des Neiges" },
  { emojis: "👻🔫🏙️", title: "SOS Fantômes" },
  { emojis: "🦈🌊🚤", title: "Les Dents de la mer" },
  { emojis: "🧑‍🚀🤖🌌", title: "Star Wars" },
  { emojis: "🧙‍♂️⚡🏰", title: "Harry Potter" },
  { emojis: "🦸‍♂️🛡️🇺🇸", title: "Captain America" },

  { emojis: "🤖🔥🚗", title: "Terminator" },
  { emojis: "🧑‍🚀🪐🌽", title: "Seul sur Mars" },
  { emojis: "🎭🔪🩸", title: "Scream" },
  { emojis: "🧠💭😴", title: "Inception" },
  { emojis: "🧑‍⚖️⚖️📜", title: "Le Parrain" },
  { emojis: "🐼🥋🏔️", title: "Kung Fu Panda" },
  { emojis: "👴🎈🏠", title: "Là-Haut" },
  { emojis: "🧑‍🍳🐀🍝", title: "Ratatouille" },
  { emojis: "🚗🧑‍🚒🔥", title: "Cars" },
  { emojis: "🧑‍🎓📚✨", title: "Harry Potter à l’école des sorciers" },

  { emojis: "👮‍♂️🏢💥", title: "Die Hard" },
  { emojis: "🧑‍🚀🌕🐒", title: "La Planète des Singes" },
  { emojis: "👽🔫🕶️", title: "Men in Black" },
  { emojis: "🧛‍♀️🐺🌕", title: "Twilight" },
  { emojis: "🧑‍✈️🛫🏝️", title: "Seul au monde" },
  { emojis: "🎩🐰⏳", title: "Alice au Pays des Merveilles" },
  { emojis: "🤡🎈🚲", title: "Ça" },
  { emojis: "🧑‍🚀🤖❤️", title: "Wall-E" },
  { emojis: "🦸‍♂️⚡🌩️", title: "Thor" },
  { emojis: "🧑‍🎤🎸🎶", title: "Rocketman" },

  { emojis: "👶🧔🔫", title: "Léon" },
  { emojis: "🧑‍🚀🚀🌍", title: "Gravity" },
  { emojis: "🧑‍⚖️🔍🧠", title: "Seven" },
  { emojis: "🤠🐎🌄", title: "Il était une fois dans l’Ouest" },
  { emojis: "👨‍👩‍👧‍👦🧬🦖", title: "Jurassic World" },
  { emojis: "🧑‍🚀🌌🌀", title: "2001, l’Odyssée de l’espace" },
  { emojis: "🎩🪄🎥", title: "The Prestige" },
  { emojis: "👻🏨❄️", title: "Shining" },
  { emojis: "🧑‍🚀🧠🤯", title: "Premier Contact" },
  { emojis: "🦸‍♂️🕷️🕸️", title: "Spider-Man No Way Home" },

  { emojis: "🧑‍🚀🌌🚀", title: "Star Wars : Un nouvel espoir" },
  { emojis: "🧑‍🚀🤖⚔️", title: "Star Wars : L’Empire contre-attaque" },
  { emojis: "🧑‍🚀👑🔥", title: "Star Wars : Le Retour du Jedi" },
  { emojis: "🧙‍♂️🪄🐍", title: "Harry Potter et la Chambre des secrets" },
  { emojis: "🧙‍♂️🔥🏆", title: "Harry Potter et la Coupe de feu" },
  { emojis: "🧙‍♂️🦉🌑", title: "Harry Potter et le Prisonnier d’Azkaban" },
  { emojis: "🧙‍♂️⚔️💀", title: "Harry Potter et les Reliques de la Mort" },

  { emojis: "🦸‍♂️🛡️💥", title: "Avengers" },
  { emojis: "🦸‍♂️🧤💎", title: "Avengers : Infinity War" },
  { emojis: "🦸‍♂️⏳💥", title: "Avengers : Endgame" },
  { emojis: "🦸‍♀️🛡️⚔️", title: "Wonder Woman" },
  { emojis: "🦸‍♂️🦇🌃", title: "The Dark Knight" },

  { emojis: "🧠🪚⏱️", title: "Saw" },
  { emojis: "👻📖😱", title: "Conjuring" },
  { emojis: "🎃🔪😨", title: "Halloween" },
  { emojis: "📞🔪😱", title: "Scream 2" },
  { emojis: "🪓❄️🏨", title: "Shining" },

  { emojis: "🎭🃏🔥", title: "Joker" },
  { emojis: "🐺💰📈", title: "Le Loup de Wall Street" },
  { emojis: "🧠🧼👊", title: "Fight Club" },
  { emojis: "🔫🍔🕺", title: "Pulp Fiction" },
  { emojis: "📦😱🔪", title: "Seven" },

  { emojis: "🎮🕶️🌍", title: "Ready Player One" },
  { emojis: "🧠🪐🌍", title: "Gravity" },
  { emojis: "🧠👽📡", title: "Premier Contact" },
  { emojis: "🧑‍🚀🌱🤖", title: "Wall-E" },
  { emojis: "🤖🧠🌃", title: "I, Robot" },

  { emojis: "🚗🔥🏁", title: "Fast & Furious 7" },
  { emojis: "🚗💣🔥", title: "Fast & Furious 9" },
  { emojis: "🚓💥🏙️", title: "Bad Boys" },
  { emojis: "🕴️🔫🍸", title: "James Bond : Skyfall" },
  { emojis: "🕵️💣🏃", title: "Mission Impossible" },

  { emojis: "🧑‍🍳🔥🍽️", title: "Julie & Julia" },
  { emojis: "🍿🎥🎭", title: "Cinema Paradiso" },
  { emojis: "🎶💃🌆", title: "La La Land" },
  { emojis: "🎪🎤✨", title: "The Greatest Showman" },
  { emojis: "🎤👑🎸", title: "Bohemian Rhapsody" },

  { emojis: "👨‍👩‍👧‍👦🏠❤️", title: "Little Miss Sunshine" },
  { emojis: "🧑‍⚖️⚖️🧠", title: "Douze hommes en colère" },
  { emojis: "🪖🇺🇸🎖️", title: "Il faut sauver le soldat Ryan" },
  { emojis: "🧑‍🚒🔥🚒", title: "Backdraft" },
  { emojis: "🏹🔥🕊️", title: "Hunger Games" },

  { emojis: "🧑‍🚀🪐🧠", title: "Moon" },
  { emojis: "🧑‍🚀🤯⏳", title: "Looper" },
  { emojis: "🦍🌆🔥", title: "King Kong" },
  { emojis: "🐉🔥👑", title: "Dragons" },
  { emojis: "🐼🥋⛰️", title: "Kung Fu Panda 2" }

];
