const films = [
  { emojis: "🧙‍♂️💍🌋", title: "Le Seigneur des Anneaux" },
  { emojis: "🧑‍🚀🌕🚀", title: "Interstellar" },
  { emojis: "🦁👑🌍", title: "Le Roi Lion" },
  { emojis: "🦖🏝️", title: "Jurassic Park" },
  { emojis: "🧛‍♂️🩸🏰", title: "Dracula" },
  { emojis: "🤠🔫🌵", title: "Le Bon, la Brute et le Truand" },
  { emojis: "🚢💔🌊", title: "Titanic" },
  { emojis: "🧠🔪🚿", title: "Psychose" },
  { emojis: "👽📞🌍", title: "E.T." },
  { emojis: "🕶️💊🖥️", title: "Matrix" },

  { emojis: "🦇🤵‍♂️🌃", title: "Batman" },
  { emojis: "🕷️🧑‍🦱🏙️", title: "Spider-Man" },
  { emojis: "🧑‍🎤👑🎵", title: "Bohemian Rhapsody" },
  { emojis: "🚗⚡🏁", title: "Fast and Furious" },
  { emojis: "🧊👸❄️", title: "La Reine des Neiges" },
  { emojis: "👻🔫🏙️", title: "SOS Fantômes" },
  { emojis: "🦈🌊🚤", title: "Les Dents de la mer" },
  { emojis: "🧑‍🚀🤖🌌", title: "Star Wars" },
  { emojis: "🧙‍♂️⚡🏰", title: "Harry Potter" },
  { emojis: "🦸‍♂️🛡️🇺🇸", title: "Captain America" },

  { emojis: "🤖🔥🚗", title: "Terminator" },
  { emojis: "🧑‍🚀🪐🌽", title: "Seul sur Mars" },
  { emojis: "🎭🔪🩸", title: "Scream" },
  { emojis: "🧠💭😴", title: "Inception" },
  { emojis: "🧑‍⚖️⚖️📜", title: "Le Parrain" },
  { emojis: "🐼🥋🏔️", title: "Kung Fu Panda" },
  { emojis: "👴🎈🏠", title: "Là-Haut" },
  { emojis: "🧑‍🍳🐀🍝", title: "Ratatouille" },
  { emojis: "🚗🧑‍🚒🔥", title: "Cars" },
  { emojis: "🧑‍🎓📚✨", title: "Harry Potter à l’école des sorciers" },

  { emojis: "👮‍♂️🏢💥", title: "Die Hard" },
  { emojis: "🧑‍🚀🌕🐒", title: "La Planète des Singes" },
  { emojis: "👽🔫🕶️", title: "Men in Black" },
  { emojis: "🧛‍♀️🐺🌕", title: "Twilight" },
  { emojis: "🧑‍✈️🛫🏝️", title: "Seul au monde" },
  { emojis: "🎩🐰⏳", title: "Alice au Pays des Merveilles" },
  { emojis: "🤡🎈🚲", title: "Ça" },
  { emojis: "🧑‍🚀🤖❤️", title: "Wall-E" },
  { emojis: "🦸‍♂️⚡🌩️", title: "Thor" },
  { emojis: "🧑‍🎤🎸🎶", title: "Rocketman" },

  { emojis: "👶🧔🔫", title: "Léon" },
  { emojis: "🧑‍🚀🚀🌍", title: "Gravity" },
  { emojis: "🧑‍⚖️🔍🧠", title: "Seven" },
  { emojis: "🤠🐎🌄", title: "Il était une fois dans l’Ouest" },
  { emojis: "👨‍👩‍👧‍👦🧬🦖", title: "Jurassic World" },
  { emojis: "🧑‍🚀🌌🌀", title: "2001, l’Odyssée de l’espace" },
  { emojis: "🎩🪄🎥", title: "The Prestige" },
  { emojis: "👻🏨❄️", title: "Shining" },
  { emojis: "🧑‍🚀🧠🤯", title: "Premier Contact" },
  { emojis: "🦸‍♂️🕷️🕸️", title: "Spider-Man No Way Home" }
];
